got something going with basic websockets
BordenJardine/knit-works pull request #2
Opened 2021-03-28 02:24 UTC by BordenJardine

Also the README is now accurate again:
I agree with you that the express generator added too much stuff we don't need, so cannibalized the parts I liked and added them to your `server.js`

I never thought I would do homework on a _saturday_

2021-03-30 22:21 UTC, oliviaruizknott requested changes
Okay you should talk me through the `server.js` and `websockets.js` files tomorrow but in the meantime we have some very serious changes to be made.

2021-03-30 22:21 UTC, oliviaruizknott commented on README.md
> +A project by Matthew Borden Jardine and Olivia Heather Ramharacksing Ruiz-Knott.
```suggestion
A project by Matthew Borden Jardine and Olivia Bethany Ramharacksingh Ruiz-Knott.
```

so close buddy

2021-03-30 22:21 UTC, oliviaruizknott commented on server.js
> -});
Are we going to be a no-semicolon project?—

2021-03-30 22:21 UTC, oliviaruizknott commented on server.js
>  });
—or not?!

2021-03-30 22:21 UTC, oliviaruizknott commented on public/index.html
> +  Knitting is Super Cool! 🧶
Are you feeling good about the use of title case here?

2021-03-30 22:23 UTC, oliviaruizknott commented on README.md
> +A project by Matthew Borden Jardine and Olivia Heather Ramharacksing Ruiz-Knott.
You may merge once this requested change has been made.

2021-03-31 01:32 UTC, BordenJardine commented on README.md
> +A project by Matthew Borden Jardine and Olivia Heather Ramharacksing Ruiz-Knott.
_fuck_

2021-03-31 01:33 UTC, BordenJardine commented on server.js
> -});
please please please

2021-03-31 01:36 UTC, merged